### numpy is the libary paltform working with numerical of data with python

In [4]:
import numpy as np

### this the normal mathmatical calculation with python 

In [5]:
w1,w2,w3= 0.3,0.2,0.5

In [6]:
kanto_temp= 73
kanto_rainfull= 67
kanto_humididty=43

In [7]:
kanto_yelid_apple= kanto_temp * w1 +kanto_rainfull*w2 + kanto_humididty +w3
kanto_yelid_apple

78.8

In [8]:
print ('the expected kanto yelid apple in kanto region is {} ton'.format(kanto_yelid_apple))

the expected kanto yelid apple in kanto region is 78.8 ton


### how to write the function to calculate all of them on one 

In [9]:
weight=[w1,w2,w3]

In [10]:
kanto =[73,67,43]
johto=[91,88,64]
hoenn=[87,134,58]
sinno=[102,43,37]
unvoe=[69,96,70]

In [11]:
kanto

[73, 67, 43]

In [12]:
weight

[0.3, 0.2, 0.5]

### zip is built in function can return tuple (x,y)

In [13]:
for items in zip(kanto,weight):
    print (items)

(73, 0.3)
(67, 0.2)
(43, 0.5)


In [14]:
for x,w in zip(kanto,weight):
    print(x)
    print(w)

73
0.3
67
0.2
43
0.5


In [15]:
def crope_yelid (region,weigth):
    result=0
    for x,y in zip(region,weight):
        result += x* y
    return result


In [16]:
crope_yelid(kanto,weight)

56.8

In [17]:
crope_yelid(johto,weight)

76.9

## goning to Numpy

In [18]:
kanto=np.array([73,67,43])
kanto

array([73, 67, 43])

In [19]:
weight=np.array([w1,w2,w3])
weight

array([0.3, 0.2, 0.5])

In [20]:
type(kanto)

numpy.ndarray

In [21]:
type(weight)

numpy.ndarray

### numpy like the list support index

In [22]:
weight[0]

0.3

In [23]:
kanto[2]

43

### operating on Numpy

In [24]:
## dot.function 
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

In [25]:
np.dot(kanto,weight)

56.8

In [26]:
np.dot(sinno,weight)

57.699999999999996

### the other way to calculate by using sum function

In [27]:
weight

array([0.3, 0.2, 0.5])

In [28]:
kanto

array([73, 67, 43])

In [29]:
weight*kanto

array([21.9, 13.4, 21.5])

In [30]:
(kanto * weight).sum()

56.8

### compare between the Numpy & python timing

In [31]:
# pytho list
arr1 = list(range(1000000))
arr2=list(range(1000000,2000000))
# Numpy array
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [32]:
%%time
result =0
for x1,x2 in zip (arr1,arr2):
    result += x1*x2
result

Wall time: 785 ms


833332333333500000

In [33]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 32 ms


-1942957984

### Multi-dimensional Numpy array

In [34]:
# this 2D Numpy array
climate_data =np.array([[73,67,43],
                       [91,88,64],
                       [87,134,58],
                       [102,43,37],
                       [69,96,70]])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [35]:
type(climate_data)

numpy.ndarray

In [36]:
# 2D array
climate_data.shape

(5, 3)

In [37]:
weight

array([0.3, 0.2, 0.5])

In [38]:
# 1D array
weight.shape

(3,)

In [39]:
# 3D array
arr3 = np.array([
               [[11,12,130],
                [14,15,16]],
    
               [[17,18,19],
               [20,21,22]]])
arr3

array([[[ 11,  12, 130],
        [ 14,  15,  16]],

       [[ 17,  18,  19],
        [ 20,  21,  22]]])

In [40]:
arr3.shape

(2, 2, 3)

In [41]:
weight.dtype

dtype('float64')

In [42]:
climate_data.dtype

dtype('int32')

In [43]:
arr3.dtype

dtype('int32')

In [44]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

###  np.matmul fanction using to working between different kind of data togather or @ function 

In [45]:
np.matmul(climate_data,weight)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [46]:
climate_data @ weight

array([56.8, 76.9, 81.9, 57.7, 74.9])

### urllib is library to add request to download the files & check it with home page of note book

In [47]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x224f4d672e0>)

In [48]:
### climate_data = np.genform txt('file name or file path', delimiter = ' ,', skip_header=1)

In [49]:
climate_data= np.genfromtxt('climate.txt', delimiter=',',skip_header=1)

In [50]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [51]:
climate_data.shape

(10000, 3)

In [52]:
weight=np.array([0.3,0.2,0.5])

In [53]:
yelid= climate_data@weight

In [54]:
%%time
yelid

Wall time: 0 ns


array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [55]:
yelid.shape

(10000,)

### can u add the yalid to original array in climat_data by using concatenate function

#### concatenate function when using need to add the orginal file u want to add to it & the other result and preformed reshape accorrding what u want 
#### also u need to identfy axis=0 is meaning add row 
#### axis =1  is meaning add column 

In [61]:
climate_result = np.concatenate((climate_data,yelid.reshape(10000 , 1)), axis=1)

In [62]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

### after using txt file and make a modification using savetxt function to save the file

In [66]:
np.savetxt('climate_result.txt',
          climate_result,
          fmt='%.2f',
          header='temp, rainfall,humid, yelid',
          comments='')

In [69]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [70]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [71]:
# add Scalar
arr2 +3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [72]:
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [73]:
arr2+arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [74]:
arr3/2

array([[5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. ],
       [9.5, 5.5, 6. , 6.5]])

In [75]:
arr3*5

array([[55, 60, 65, 70],
       [75, 80, 85, 90],
       [95, 55, 60, 65]])

In [76]:
arr2.shape

(3, 4)

In [77]:
arr4=np.array([4,5,6,7])

In [78]:
arr4.shape

(4,)

In [79]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [81]:
arr4_replicated=np.array([[4,5,6,7],
                        [4,5,6,7],
                        [4,5,6,7]])

In [82]:
arr4_replicated

array([[4, 5, 6, 7],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [84]:
arr2+arr4_replicated

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [85]:
arr5= np.array([7,8])

In [86]:
arr5.shape

(2,)

In [87]:
arr2+arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [96]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[2,2,3],[4,5,5]])

In [98]:
arr1==arr2

array([[False,  True,  True],
       [ True,  True, False]])

In [97]:
arr1!=arr2

array([[ True, False, False],
       [False, False,  True]])

In [99]:
arr1>=arr2

array([[False,  True,  True],
       [ True,  True,  True]])

### can check all the array and working on it with arthimatical operational & bool 

### also u can using sum method to sum the number of the true values all the true value= 1

### false values =0

In [100]:
arr1< arr2

array([[ True, False, False],
       [False, False, False]])

In [101]:
(arr1== arr2).sum()

4

In [102]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [103]:
arr3.shape

(3, 2, 4)

### u can using index method to path any value u want inside the array

In [104]:
## Single element
arr3[1,1,2]

36.0

In [105]:
##sub array using range
arr3[1:,0:1,:2]


array([[[15., 16.]],

       [[98., 32.]]])

In [106]:
arr3[1:,0:1,:2].shape

(2, 1, 2)

 ### Can u creating Numpy array by other way

In [107]:
# all Zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [108]:
## all ones 
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [109]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [111]:
# Random vector
np.random.rand(5)

array([0.58139777, 0.23572796, 0.87179194, 0.43452258, 0.99260045])

In [113]:
# Random matrix
np.random.randn(2,3)

array([[ 0.91802463,  0.76004353,  1.03940905],
       [ 0.31357534, -0.87306902, -0.80267232]])

## What is diff between rand & randn
#### rand  ====> has range from 0 to 1
#### randn ====> has range from -2 to 2 

In [114]:
# fix value
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [120]:
# range with start end & step
np.arange(10, 9, 3)

array([], dtype=int32)

In [117]:
# equally spaced number in range
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [122]:
np.linspace(3,27,9).reshape(3,3)

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]])

# Interacting with OS  (operating system)and file systeme

In [124]:
import os

### TO check work directory

In [125]:
os.getcwd()

'C:\\Users\\2m\\Desktop\\data analysis jovain\\Jovian ML'

In [126]:
help(os.listdir)

Help on built-in function listdir in module nt:

listdir(path=None)
    Return a list containing the names of the files in the directory.
    
    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.
    
    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.



In [129]:
# Relative Path
os.listdir('.')

['.ipynb_checkpoints',
 '.jovianrc',
 'climate.txt',
 'climate_result.txt',
 'jovian ML lecture 2 loops.ipynb',
 'Jovian ML Lecture 3 Numpay.ipynb',
 'Jovian.ML  1 st Lecture .ipynb',
 'Jovian.ML Lecture2.ipynb']

### To CHECK the sub directory

In [132]:
#Absolut Path
os.listdir('/users')

['2m', 'All Users', 'Default', 'Default User', 'desktop.ini', 'Public']

In [134]:
os.listdir('/users/2m')

['.atom',
 '.bashrc',
 '.bash_history',
 '.conda',
 '.condarc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jovian',
 '.jupyter',
 '.matplotlib',
 '.spyder-py3',
 '.vscode',
 '3D Objects',
 'anaconda3',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'edb_npgsql.exe',
 'edb_pgjdbc.exe',
 'edb_psqlodbc.exe',
 'edb_psqlodbc.exe-20200819143059',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'mu_array.npy',
 'My Documents',
 'my_array.npy',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'postgresql_10.exe',
 'postgresql_12.exe',
 'PrintHood',
 'PycharmProjects',
 'Recent',
 'S

In [135]:
os.makedirs('./data',exist_ok=True)

In [136]:
os.listdir('.')

['.ipynb_checkpoints',
 '.jovianrc',
 'climate.txt',
 'climate_result.txt',
 'data',
 'jovian ML lecture 2 loops.ipynb',
 'Jovian ML Lecture 3 Numpay.ipynb',
 'Jovian.ML  1 st Lecture .ipynb',
 'Jovian.ML Lecture2.ipynb']

In [137]:
'data' in os.listdir('.')

True

In [139]:
os.listdir('./data')

[]

## After we creat the data file let us download some files on it

In [147]:
url1='https://hub.jovian.ml/wp-content/uploads/2020/08/loans1.txt'
url2='https://hub.jovian.ml/wp-content/uploads/2020/08/loans2.txt'
url3='https://hub.jovian.ml/wp-content/uploads/2020/08/loans3.txt'

In [148]:
import urllib.request

In [149]:
urllib.request.urlretrieve(url1,'./data/loans1.txt')

('./data/loans1.txt', <http.client.HTTPMessage at 0x224f9b0d400>)

In [151]:
urllib.request.urlretrieve(url2,'./data/loans2.txt')

('./data/loans2.txt', <http.client.HTTPMessage at 0x224f9b0d100>)

In [152]:
urllib.request.urlretrieve(url2,'./data/loans3.txt')

('./data/loans3.txt', <http.client.HTTPMessage at 0x224f9b0da90>)

In [153]:
os.listdir('./data')

['loans1.txt', 'loans2.txt', 'loans3.txt']

## Reading from Files

In [155]:
file1= open('./data/loans1.txt', mode='r')

In [156]:
file1_content= file1.read()

In [158]:
file1_content

'amount,duration,rate,down_payment\n100000,36,0.08,20000\n200000,12,0.1,\n628400,120,0.12,100000\n4637400,240,0.06,\n42900,90,0.07,8900\n916000,16,0.13,\n45230,48,0.08,4300\n991360,99,0.08,\n423000,27,0.09,47200'

In [157]:
print(file1_content)

amount,duration,rate,down_payment
100000,36,0.08,20000
200000,12,0.1,
628400,120,0.12,100000
4637400,240,0.06,
42900,90,0.07,8900
916000,16,0.13,
45230,48,0.08,4300
991360,99,0.08,
423000,27,0.09,47200


In [159]:
file1.close()

# Close the files automatically using with

In [161]:
with open ('./data/loans2.txt') as file:
    file2_content = file.read()
    print(file2_content)

amount,duration,rate,down_payment
828400,120,0.11,100000
4633400,240,0.06,
42900,90,0.08,8900
983000,16,0.14,
15230,48,0.07,4300



In [162]:
# by using with function this is close file direct just u leave it .
file.read()

ValueError: I/O operation on closed file.

# Read file line by line

In [167]:
with open('./data/loans3.txt','r') as file3:
    file3_content= file3.readlines()


In [168]:
file3_content

['amount,duration,rate,down_payment\n',
 '828400,120,0.11,100000\n',
 '4633400,240,0.06,\n',
 '42900,90,0.08,8900\n',
 '983000,16,0.14,\n',
 '15230,48,0.07,4300\n']

In [169]:
file3_content[0].strip()

'amount,duration,rate,down_payment'

# Processing data from files

In [171]:
print(file2_content)

amount,duration,rate,down_payment
828400,120,0.11,100000
4633400,240,0.06,
42900,90,0.08,8900
983000,16,0.14,
15230,48,0.07,4300



In [172]:
'828400,120,0.11,100000'.split()

['828400,120,0.11,100000']

In [173]:
loans=[{'amount':828400, 'duration': 120, 'rate': 0.11, 'down_payment':100000},
       {'amount':4633400, 'duration': 240, 'rate': 0.06, 'down_payment':'NA'},
       {'amount':828400, 'duration': 120, 'rate': 0.11, 'down_payment':100000}]

In [174]:
loans

[{'amount': 828400, 'duration': 120, 'rate': 0.11, 'down_payment': 100000},
 {'amount': 4633400, 'duration': 240, 'rate': 0.06, 'down_payment': 'NA'},
 {'amount': 828400, 'duration': 120, 'rate': 0.11, 'down_payment': 100000}]

In [175]:
print(loans)

[{'amount': 828400, 'duration': 120, 'rate': 0.11, 'down_payment': 100000}, {'amount': 4633400, 'duration': 240, 'rate': 0.06, 'down_payment': 'NA'}, {'amount': 828400, 'duration': 120, 'rate': 0.11, 'down_payment': 100000}]


 ## parse_header function which take a line as input& return a list of column header 

In [248]:
def Parse_headers(header_line):
    return header_line.strip().split(',')

In [249]:
file3_content[0]

'amount,duration,rate,down_payment\n'

In [252]:
header= Parse_headers(file3_content[0])

In [253]:
header

['amount', 'duration', 'rate', 'down_payment']

In [ ]:
## Parse_values which take data line & return list of float numbers

In [222]:
def Parse_values(data_line):
    values=[]
    for item in data_line.strip().split(','):
        values.append(float(item))
    return values

In [223]:
file3_content[1]

'828400,120,0.11,100000\n'

In [224]:
Parse_values(file3_content[1])

[828400.0, 120.0, 0.11, 100000.0]

In [225]:
Parse_values(file3_content[2])

ValueError: could not convert string to float: ''

In [226]:
file3_content[2]

'4633400,240,0.06,\n'

In [227]:
file3_content[2].strip().split(',')

['4633400', '240', '0.06', '']

In [228]:
float('')

ValueError: could not convert string to float: ''

In [229]:
## so here i need to handel this above error

In [237]:
def Parse_values(data_line):
    values=[]
    for item in data_line.strip().split(','):
        if item == '':
            values.append(0.0)
        else:
            values.append(float(item))
    return values

In [238]:
file3_content[2]

'4633400,240,0.06,\n'

In [239]:
Parse_values(file3_content[1])

[828400.0, 120.0, 0.11, 100000.0]

In [240]:
Parse_values(file3_content[2])

[4633400.0, 240.0, 0.06, 0.0]

In [241]:
## define create_item_dict which take a list of values & list of header as input and conerted to dictionary

In [261]:
def create_item_dict (values,header):
    result={}
    for value, header in zip(values, header):
        result[header]= value
    return result

In [262]:
file3_content[1]

'828400,120,0.11,100000\n'

In [263]:
values1=Parse_values(file3_content[1])

In [264]:
values1

[828400.0, 120.0, 0.11, 100000.0]

In [265]:
header

['amount', 'duration', 'rate', 'down_payment']

In [266]:
create_item_dict(values1,header)

{'amount': 828400.0, 'duration': 120.0, 'rate': 0.11, 'down_payment': 100000.0}

## Read function

In [268]:
def read_csv(file_path):
    result=[]
    # for open the file in read mode
    with open(path,'r') as f:
        # to get the list of line 
        lines=f.readlines()
        headers =Parse_headers(lines[0])
        for data_line in lines:
            # parse_ values for all lines
            values= Parse_values(lines[1:])
            # create a dict 
            item_dict= create_item_dict(values,headers)
            result.append(item_dict)
    return result

In [269]:
with open('./data/loans2.txt') as file2:
    print(file2.read())
   

amount,duration,rate,down_payment
828400,120,0.11,100000
4633400,240,0.06,
42900,90,0.08,8900
983000,16,0.14,
15230,48,0.07,4300



In [271]:
read_csv('./data/loans2.txt')

NameError: name 'path' is not defined